//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraveloggiaREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int JournalID { get; set; }
        public string Text { get; set; }
        public Nullable<int> SiteID { get; set; }
        public string KeyWords { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> JournalDate { get; set; }
        public Nullable<bool> FromPhone { get; set; }
        public string Title { get; set; }
        public Nullable<int> MemberID { get; set; }
    }
}
