//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REST_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapListItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MapListItem()
        {
            
        }
    
        public int MapID { get; set; }
        public string MapName { get; set; }
        public int MemberID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
       
    }
}
