//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REST_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class traveloggiaDBEntities : DbContext
    {
        public traveloggiaDBEntities()
            : base("name=traveloggiaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<TraveloggiaEdition> TraveloggiaEditions { get; set; }
        public virtual DbSet<Unhandled> Unhandleds { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<Journal> Journals { get; set; }
        public virtual DbSet<Map> Maps { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
    }
}
