//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraveloggiaREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public int SiteID { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<int> MapID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<bool> FromPhone { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<decimal> AverageRating { get; set; }
        public Nullable<int> VotesCast { get; set; }
        public Nullable<int> RouteIndex { get; set; }
        public Nullable<System.DateTime> Arrival { get; set; }
        public Nullable<System.DateTime> Departure { get; set; }
    }
}
