//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unhandled
    {
        public int RecordID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ExceptionName { get; set; }
        public string Message { get; set; }
        public string StackTrace { get; set; }
        public string Data { get; set; }
        public string InnerException { get; set; }
        public string PhoneID { get; set; }
        public string OS { get; set; }
        public string Model { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<int> MemberID { get; set; }
    }
}
